project:
  type: website

website:
  site-url: "https://abigailwsmith.github.io/"
  title: "Abigail Smith"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: courses.qmd
        text: Completed Courses
      - href: projects.qmd
        text: Projects
      - text: Get in touch
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/abigail-smith-57765b221/
            target: _blank
          - icon: envelope
            text: Email
            href: mailto:awsmit22@stlawu.edu
          - icon: github
            text: GitHub
            href: https://github.com/abigailwsmith
            target: _blank

format:
  html:
    page-layout: full
    sidebar: false
    theme: cosmo
    css: styles.css
    toc: true